### ISSUE TITLE
Misleading Modrinth info

### ISSUE THREAD

**Issue by FancyBaguette** [VisiVersa/Sanguine#1]
The modrinth page claims that this is a serverside only mod (there's only the "Server" badge without any other requirement info), but in order for the items to display correctly the mod needs to be installed on the clientside too, because otherwise bugs like the one shown below appear

![](https://media.discordapp.net/attachments/886291542187315230/1078360447809490964/image.png)

**Comment by DeWonknuOff** [comment]
Hello, Idk if visi answer here so you can join on the discord of visi (https://discord.gg/hYzjGmjdnp) and there you can tell it, Btw this is a page for the **datapack** (that its different than a **mod**).
